services:
  # service name
  app:
    build:
      context: ./..
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    # map src to container
    volumes:
      - ./../:/app
    environment:
      - APP_ENV=local
    healthcheck:
      test: "curl -f http://localhost:8000/heartbeat/readiness || exit 1"
      interval: 20s
      timeout: 3s
      retries: 10
    networks:
      - fastapi-network
    # depends on mysql
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    build:
      context: ./..
      dockerfile: ./docker/mysql/Dockerfile
    # MySQL automatically executes all .sql files in this directory during initialization
    volumes:
      - ./../docker/mysql/fixtures:/docker-entrypoint-initdb.d
    healthcheck:
      # `SELECT 1` is a simple query to verify database is responsive
      # mysql -utest -ptest fastapi -e 'select 1'
      # mysql -utest -ptest fastapi -e 'show tables'
      # mysql -utest -ptest fastapi -e 'select * from posts'
      test: "mysql -u$${MYSQL_USER} -p$${MYSQL_PASSWORD} $${MYSQL_DATABASE} -e 'SELECT 1'"
      interval: 2s
      timeout: 15s
      retries: 15
    networks:
      - fastapi-network

networks:
  fastapi-network:
    driver: bridge
